name: 🐞Bug report
description: Create a report to help us improve
# title: "[Bug]: "
labels: ["bug"]
body:
- type: checkboxes
  id: check_existing_issues
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: describe_the_bug
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  id: expected_behavior
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  id: to_reproduce
  attributes:
    label: To Reproduce
    description: When does the bug occur? Please write down the steps to reproduce the bug.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ## Execution environment
      You may skip the questions, but please write as much as possible.
- type: input
  id: application_version
  attributes:
    label: Application version
    description: You can check the properties of the .exe file or from the "About this app" window.
    placeholder: |
      0.3.20, 0.1.52, 0.2.4, etc.
  validations:
    required: false
- type: textarea
  id: os_version
  attributes:
    label: OS Version
    description: You can check this by pressing Win + Pause key.
    placeholder: |
      Edition	Windows 11 Pro
      Version	22H2
      Installed on	2022/11/06
      OS build	22621.1778
      Experience	Windows Feature Experience Pack 1000.22642.1000.0
    render: TSV
  validations:
    required: false
- type: textarea
  id: dotnet_runtime_version
  attributes:
    label: .NET Runtime Version
    description: "You can check this by running the `dotnet --list-runtimes` command."
    placeholder: |
      Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  validations:
    required: false
- type: textarea
  id: additional_context
  attributes:
    label: Additional context
    description: |
      Please add any other context about the problem here. Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. (Make sure that the log file does not contain any sensitive information!)
  validations:
    required: false
