name: 🐞バグ報告
description: バグを報告していただけると助かります！
# title: "[Bug]: "
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: "Issueを確認しましたか？"
    description: "あなたが遭遇したバグについて、すでにIssueが存在しないかどうか検索してください。"
    options:
    - label: "既存のIssueを検索してみました"
      required: true
- type: input
  attributes:
    label: "バグの説明"
    description: "バグの内容を明確かつ簡潔に説明してください。"
  validations:
    required: true
- type: textarea
  attributes:
    label: "期待していた動作"
    description: "期待していた動作を明確かつ簡潔に説明してください。"
  validations:
    required: true
- type: textarea
  attributes:
    label: "再現手順"
    description: "そのバグはどのようなときに発生しますか？バグを再現するための手順を教えてください。"
    placeholder: |
      "1. ...を...に設定"
      "2. '...'を実行"
      "3. ...というエラーが発生"
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      "## 実行環境"
      "不明な項目は飛ばしても構いませんが、出来るだけ埋めていただけると助かります。"
- type: input
  attributes:
    label: "アプリケーションのバージョン"
    description: ".exeファイルのプロパティや、「このアプリについて」ウィンドウから確認することができます。"
    placeholder: |
      "0.3.20, 0.1.52, 0.2.4など"
  validations:
    required: false
- type: input
  attributes:
    label: "OSのバージョン"
    description: "Win＋Pauseキーなどで確認できると思います。"
    placeholder: |
      Windows 10 Pro 20H2
  validations:
    required: false
- type: textarea
  attributes:
    label: ".NETランタイムのバージョン"
    description: "`dotnet --list-runtimes` コマンドを実行することで確認できると思います。"
    placeholder: |
      Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  validations:
    required: false
- type: textarea
  attributes:
    label: "その他"
    description: |
      "問題に関するその他の説明事項がある場合は、ここに何でも書いてください。"

      "Tip: この領域をクリックしてハイライトし、ファイルをドラッグすることで、画像やログファイルを添付することもできます。(ログファイルには機密情報が含まれていないことを確認してください！)"
  validations:
    required: false
