contact_links:
  - name: Google form (日本語 or English)
    url: https://forms.gle/WevPFNfJR5FRphi37
    about: 匿名でフィードバックを送る。Anonymous feedback.
  - name: よくある質問 (FAQ)
    url: https://skyzibackup.skyzi.jp/faq
    about: よくある質問とその回答です。
  - name: Encrypted mail form(FlowCrypt)
    url: https://flowcrypt.com/me/skyzi000
    about: Use this contact page to send me encrypted messages and files.
