name: ✨Feature request
description: Any new ideas you can suggest would be greatly appreciated!
labels: ["enhancement"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if a similar Issue already exists.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  attributes:
    label: Is your feature request related to a problem?
    description: A clear and concise description of what the problem is.
    placeholder: I'm always frustrated when [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Solutions or desired features
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: |
      Please add any other context for this here. Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. (Make sure that the log file does not contain any sensitive information!)
  validations:
    required: false
