name: ✨Feature request
description: Any new ideas you can suggest would be greatly appreciated!
labels: ["enhancement"]
body:
- type: checkboxes
  id: check_existing_issues
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if a similar Issue already exists.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: is_your_feature_request_related_to_a_problem
  attributes:
    label: Is your feature request related to a problem?
    description: A clear and concise description of what the problem is.
    placeholder: I'm always frustrated when [...]
  validations:
    required: false
- type: textarea
  id: solutions_or_desired_features
  attributes:
    label: Solutions or desired features
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  id: alternatives_youve_considered
  attributes:
    label: Alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  id: additional_context
  attributes:
    label: Additional context
    description: |
      Please add any other context for this here. Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. (Make sure that the log file does not contain any sensitive information!)
  validations:
    required: false
