theme: jekyll-theme-cayman
show_downloads: true
github:
  release_url: https://github.com/Skyzi000/SkyziBackup/releases
lang: ja
google_analytics_4: G-JB6HFY9JHS
og_image: https://raw.githubusercontent.com/Skyzi000/SkyziBackup/main/images/SkyziBackup_128.png
