# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: Build

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - "**.md"
    # Publish version tags as releases.
    tags: ["v*.*"]
jobs:
  build:
    strategy:
      matrix:
        configuration: [ Release, Debug ]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: SkyziBackup.sln                            # Replace with your solution name, i.e. MyWpfApp.sln.
#      Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
#      Wap_Project_Directory: your-wap-project-directory-name    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: SkyziBackup.csproj                      # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
      SONAR_ENABLED: ${{ secrets.SONAR_TOKEN != '' }}

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 6.0.x

#     # Execute all unit tests in the solution
#     - name: Execute unit tests
#       run: dotnet test

    - name: Cache SonarCloud packages
      if: env.SONAR_ENABLED == 'true'
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Install SonarScanner (tool)
      if: env.SONAR_ENABLED == 'true'
      run: dotnet tool install --global dotnet-sonarscanner
      shell: pwsh
        
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore $env:Solution_Name -r win-x64 /p:Configuration=$env:Configuration /p:Platform="x64" /p:PublishReadyToRun=true
      env:
        Configuration: ${{ matrix.configuration }}

#     # Decode the base 64 encoded pfx and save the Signing_Certificate
#     - name: Decode the pfx
#       run: |
#         $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
#         $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath GitHubActionsWorkflow.pfx
#         [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

#     # Create the app package by building and packaging the Windows Application Packaging project
#     - name: Create the app package
#       run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration # /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
#       env:
#         Appx_Bundle: Always
#         Appx_Bundle_Platforms: x64
#         Appx_Package_Build_Mode: StoreUpload
#         Configuration: ${{ matrix.configuration }}

    - name: Sonar Begin
      if: env.SONAR_ENABLED == 'true'
      shell: pwsh
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        $ErrorActionPreference = 'Stop'
        dotnet sonarscanner begin `
          /k:"Skyzi000_SkyziBackup" `
          /o:"skyzi000" `
          /d:sonar.host.url="https://sonarcloud.io" `
          /d:sonar.token="$env:SONAR_TOKEN"
        if ($LASTEXITCODE -ne 0) { throw "Sonar BEGIN failed $LASTEXITCODE" }

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        Configuration: ${{ matrix.configuration }}
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        dotnet publish $env:Solution_Name -r win-x64 -v n --no-restore /p:Configuration=$env:Configuration /p:Platform="x64" /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:SelfContained=false
        if ($LASTEXITCODE -ne 0) { throw "BUILD failed $LASTEXITCODE" }
        
    - name: Sonar End
      if: env.SONAR_ENABLED == 'true'
      shell: pwsh
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        $ErrorActionPreference = 'Stop'
        dotnet sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"
        if ($LASTEXITCODE -ne 0) { throw "Sonar END failed $LASTEXITCODE" }
        
#     # Remove the pfx
#     - name: Remove the pfx
#       run: Remove-Item -path $env:Wap_Project_Directory\$env:Signing_Certificate

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Win-x64-${{ matrix.configuration }}-${{ github.sha }}
        path: bin\x64\${{ matrix.configuration }}\net6.0-windows\win-x64\publish\
#         name: MSIX Package
#         path: ${{ env.Wap_Project_Directory }}\AppPackages

  release:
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    env:
      APPLICATION_NAME: SkyziBackup
    runs-on: ubuntu-latest
    steps:

      # デフォルトで入ってるのでインストールする必要はない
      # - name: Install p7zip
      #   run: |
      #     sudo add-apt-repository universe
      #     sudo apt update
      #     sudo apt install p7zip

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Download build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: Win-x64-Release-${{ github.sha }}
          path: ${{ env.APPLICATION_NAME }}_${{ steps.get_tag.outputs.TAG }}

      # .pdbファイルを削除してから.7zと.zipに圧縮する
      - name: Archive exe files
        run: |
          find ./${{ env.APPLICATION_NAME }}_${{ steps.get_tag.outputs.TAG }}/ -name '*.pdb' -type f -delete
          mkdir Release
          7z a -mx=9 ./Release/${{ env.APPLICATION_NAME }}_${{ steps.get_tag.outputs.TAG }}.7z ${{ env.APPLICATION_NAME }}_${{ steps.get_tag.outputs.TAG }}
          zip -r ./Release/${{ env.APPLICATION_NAME }}_${{ steps.get_tag.outputs.TAG }}.zip ${{ env.APPLICATION_NAME }}_${{ steps.get_tag.outputs.TAG }}

      # CHANGELOG.mdから最新タグの情報を抜き出してリリースノートを作る
      - name: Create release note
        run: |
          cat ./CHANGELOG.md | sed '1,/^## /d;/^## /,$d' >| ./release.md

      # SHA-256を計算してリリースノートに追記する
      - name: Calculate hash of files
        run: |
          echo '<details><summary>SHA-256 Hash</summary>' >> ./release.md
          printf "\n%s\n" '```' >> ./release.md
          sha256sum ${{ env.APPLICATION_NAME }}_${{ steps.get_tag.outputs.TAG }}/SkyziBackup.exe >> ./release.md
          cd Release
          sha256sum * >> ../release.md
          cd ..
          printf "%s\n" '```' >> ./release.md
          echo '</details>' >> ./release.md

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ./release.md
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          files: |
            ./Release/${{ env.APPLICATION_NAME }}_${{ steps.get_tag.outputs.TAG }}.7z
            ./Release/${{ env.APPLICATION_NAME }}_${{ steps.get_tag.outputs.TAG }}.zip
